# ------------------------------------
#   官方手册: https://manual.serverless-devs.com/user-guide/aliyun/#fc3
#   有问题快来钉钉群问一下吧：33947367
# ------------------------------------

edition: 3.0.0
name: fastify-yishan-api
access: "default"
vars:
  region: "cn-shanghai"
  functionName: "fastify-yishan-api"
resources:
  start_fastify:
    component: fc3
    actions:
      pre-deploy:
    props:
      region: ${vars.region}
      description: Fastify Yishan API
      runtime: custom.debian12
      timeout: 60
      cpu: 2
      memorySize: 4096
      diskSize: 512
      instanceConcurrency: 100
      layers:
        - acs:fc:${vars.region}:official:layers/Nodejs22/versions/1
      environmentVariables:
        PATH: >-
          /opt/nodejs22/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
        NODE_PATH: >-
          /opt/nodejs/node_modules
      customRuntimeConfig:
        command:
          - node
          - --env-file=.env
          - ./server.js
        port: 3000
      functionName: ${vars.functionName}
      code: ./dist
      triggers:
        - triggerName: httpTrigger
          triggerType: http
          triggerConfig:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
